
const images = [
    {id: 0, col:'A', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 1, col:'A', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 2, col:'A', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 3, col:'A', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 4, col:'A', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 5, col:'A', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 6, col:'A', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 7, col:'A', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    {id: 8, col:'B', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 9, col:'B', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 10, col:'B', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 11, col:'B', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 12, col:'B', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 13, col:'B', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 14, col:'B', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 15, col:'B', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    {id: 16, col:'C', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 17, col:'C', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 18, col:'C', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 19, col:'C', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 20, col:'C', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 21, col:'C', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 22, col:'C', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 23, col:'C', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    {id: 24, col:'D', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 25, col:'D', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 26, col:'D', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 27, col:'D', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 28, col:'D', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 29, col:'D', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 30, col:'D', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 31, col:'D', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    {id: 32, col:'E', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 33, col:'E', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 34, col:'E', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 35, col:'E', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 36, col:'E', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 37, col:'E', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 38, col:'E', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 39, col:'E', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    {id: 40, col:'F', row: 1, src: require('../../images/A1.jpg'), title: 'Image of section A1', alt: 'Unspecidied'},
    {id: 41, col:'F', row: 2, src: require('../../images/A2.jpg'), title: 'Image of section A2', alt: 'Unspecidied'},
    {id: 42, col:'F', row: 3, src: require('../../images/A3.jpg'), title: 'Image of section A3', alt: 'Unspecidied'},
    {id: 43, col:'F', row: 4, src: require('../../images/A4.jpg'), title: 'Image of section A4', alt: 'Unspecidied'},
    {id: 44, col:'F', row: 5, src: require('../../images/A5.jpg'), title: 'Image of section A5', alt: 'Unspecidied'},
    {id: 45, col:'F', row: 6, src: require('../../images/A6.jpg'), title: 'Image of section A6', alt: 'Unspecidied'},
    {id: 46, col:'F', row: 7, src: require('../../images/A7.jpg'), title: 'Image of section A7', alt: 'Unspecidied'},
    {id: 47, col:'F', row: 8, src: require('../../images/A8.jpg'), title: 'Image of section A8', alt: 'Unspecidied'},
    
];

export default images;